[package]
name = "minitable_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
darling = "0.20.10"
proc-macro2 = "1.0.86"
quote = "1.0.37"
slab = "0.4.9"
syn = "2.0.77"

[lib]
proc-macro = true
