[package]
name = "minitable"
version = "0.1.0"
edition = "2021"

[dependencies]
minitable_derive = { path = "../minitable_derive" }
slab = { workspace = true }
ahash = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "graph"
harness = false
